//
//  Article.swift
//  ReflectorIOS
//
//  Created by Nikhil Menon on 4/4/20.
//  Copyright © 2020 Nikhil Menon. All rights reserved.
//

import Foundation
import SwiftUI

/*
 Example of what an article looks like from a GET Request
 <item>
     <title>MSU moves to optional pass/fail grading system</title>
     <description>Mississippi State University announced Monday that they would be going to an optional
                    pass/fail grading system. According to the university press release, students will be allowed
                        to choose per individual course to keep their actual letter grade or to change&#8230;</description>
     <pubDate>Mon, 06 Apr 2020 19:02:00 -0500</pubDate>
     <guid isPermaLink="false">http://www.reflector-online.com/tncms/asset/editorial/0bc5eefa-7863-11ea-9bc4-ab8dc9145847</guid>
     <link>http://www.reflector-online.com/news/article_0bc5eefa-7863-11ea-9bc4-ab8dc9145847.html</link>
     <dc:creator>Hannah Blankenship | Managing Editor</dc:creator>
 </item>
 
 */

/// This is an Article data model.
struct Article: Identifiable {
    /// Unique id generated by SwiftUI.
    let id = UUID()
    /// The headline of the article
    var title: String?
    /// This is  the short description of the article
    var details: String?
    /// Publish date
    var pubDate: Date?
    /// Link to full HTML article
    var link: String?
    /// author of the articles
    var creator: String?
}

// MARK: - Debugging

extension Article {
    func debug_print() {
        print("==== ARTICLE DEBUG ====")
        print("Title: \(title ?? "NOT AVAILABLE")")
        print("Desc: \(details ?? "NOT AVAILABLE")")
        print("Date Published: \(String(describing: pubDate))")
        print("Link: \(link ?? "NOT AVAILABLE")")
        print("Creator: \(creator ?? "NOT AVAILABLE")")
    }
}

// MARK: - Equatable

extension Article: Equatable {
    static func == (lhs: Article, rhs: Article) -> Bool {
        return lhs.id == rhs.id
    }
}
